### ISSUE TITLE
Últimos cambios se ha perdido commit de hace 1 año

### ISSUE THREAD

**Issue by alxarafe** [NeoRazorX/modelo_347#2]
Con los últimos cambios se ha perdido este commit y la asesoría indica que el 347 está mal:

https://github.com/NeoRazorX/modelo_347/commit/11dda6da51a20547caa28812ae59946c6f35ac50

En los cambios de los últimos commits ni aparece que se haya hecho este cambio, da la impresión que se ha hecho un push forzado, como si el repositorio no hubiera estado sincronizado.

**Comment by NeoRazorX** [comment]
Solucionado. Gracia ;-)
